Make sync script exit early on failure (#198)
Right now they run until end, and due to the large
size of this repo it can sometimes be hard to see if
something broken part way through the run.
So break when things break, in a bigger and more
obvious way!

https://phabricator.wikimedia.org/T298771

diff --git a/sync/pacman/pacman-script b/sync/pacman/pacman-script
--- a/sync/pacman/pacman-script
+++ b/sync/pacman/pacman-script
@@ -3,6 +3,9 @@
 # this directory must include a pacman.yml
 # pacman will populate a dist folder in the same directory, from the pacman.yml
 
+# exit when any command fails
+set -e
+
 if [ -z "$1" ]; then
     echo "Usage: $0 <target>"
     exit 1
